trigger:
- master

pr:
- master

pool: Linux

steps:
- template: /steps/validate-template.yml
  parameters:
    templates:
    - name: ./steps/dotnet/test.yml
      type: step
    
    - name: ./jobs/dotnet/nuget-package.yml
      type: job

