#trigger:
#- master

#pr:
#- master

pool: Linux

steps:
- template: /steps/validate-template.yml
  parameters:
    templates:
    - name: /steps/dotnet/test.yml
      type: step
      parameters:
      - blah: blah
    
    - name: /jobs/dotnet/nuget-package.yml
      type: job
      parameters:
      - blah: blah
