parameters:
  pool: 'Linux'
  environment: ''
  variables: []
  artifact: ''
  feed: ''
  dependsOn: ''
  condition: true
  dotnetSdkVersion: '3.x'

jobs:
- deployment:
  displayName: Deploy ${{ parameters.artifact }} to ${{ parameters.environment }}
  pool: ${{ parameters.pool }}

  workspace:
    clean: all
    
  ${{ if parameters.dependsOn }}:
    dependsOn: ${{ parameters.dependsOn }}

  ${{ if parameters.condition }}:
    condition: ${{ parameters.condition }}

  variables:
    ${{ insert }}: ${{ parameters.variables }}
    _DotNetSdkVersion: ${{ parameters.dotnetSdkVersion }}

  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: ${{ parameters.artifact }}

        - task: UseDotNet@2
          displayName: Install .NET Core
          inputs:
            packageType: sdk
            version: $(_DotNetSdkVersion)

        - task: DotNetCoreCLI@2
          displayName: Push Packages
          inputs:
            command: push
            packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
            nuGetFeedType: external
            externalEndpoint: ${{ parameters.feed }} # Service Connection Name
            publishPackageMetadata: true
            verbosityPush: Normal
